### ISSUE TITLE
Upgrade of helm broken

### ISSUE THREAD

**Issue by notsag** [gantsign/ansible_role_helm#44]
Hello,

I noticed that the upgrade of helm is broken.
I tried upgrading from `3.0.2` to `3.1.2` by changing the variable `helm_version`.
The download works fine but the install step never occurs because the helm version check never returns an `rc == 0`.

It looks like the template used in this command is incorrect : 
```
{{ helm_install_dir }}/helm version --client --template {{ "'{{ .Client.SemVer }}'" }}
```

**Comment by freemanjp** [comment]
@notsag thanks for the pull request. You can find your fix in version [2.1.3](https://github.com/gantsign/ansible_role_helm/releases/tag/2.1.3) of this role.
